### ISSUE TITLE
flash時WindowsError:[Error 21]が出る問題

### ISSUE THREAD

**Issue by KenshiroHosaka** [Takaaki-MATSUZAWA/MATSU-bed-cli#2]
https://github.com/hardtail0112/MATSU-bed-cli/blob/4bcf9fddfcbb5e0c73c931095f8fa2017bdb35b2/matsubed/matsubed.py#L115

DVDドライブ(E:)、matsubed(F:)と認識されているとき
`matsubed flash`
をすると、以下のエラーが出て書き込みに失敗する

D:\matsubed-workspace\test>matsubed flash

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\Scripts\matsubed-script.py", line 11, in <module>
    load_entry_point('MATSU-bed-cli==0.1.0', 'console_scripts', 'matsubed')()
  File "build\bdist.win-amd64\egg\matsubed\matsubed.py", line 249, in main
  File "build\bdist.win-amd64\egg\matsubed\matsubed.py", line 120, in flash
  File "build\bdist.win-amd64\egg\matsubed\matsubed.py", line 95, in format
WindowsError: [Error 21] デバイスの準備ができていません。: 'E:/*.*'

DVDドライブの割り当て文字をGとかにして、matsubedの割り当て文字がE（DVDドライブの割り当て文字より前の文字）になると
`Success firmware update !!!`
となり、書き込みに成功する

**Comment by hardtail0112** [comment]
flash()の中のformat()で接続されてるドライブの中で*.binが1つだけ入ってるものを上から順番に探していくけど、何も入ってない光学ドライブの中でファイルがあるか確認しようとしてるからエラー吐かれてるみたい。

例外処理をかけば多分解決する

**Comment by Takaaki-MATSUZAWA** [comment]
flash()のformat()とwrite()に例外処理を追加して解決しました。
version 0.2.1です。
